import yaml

from hippo_brain.vault_render import (
    NodeRow,
    entity_slug,
    node_source_key,
    render_node_note,
    slugify,
)


def test_slugify_strips_obsidian_reserved_chars():
    # concept canonicals are raw error text with [ ] : / " and #
    assert slugify("error[E0382]: borrow of moved value") == "error-e0382-borrow-of-moved-value"
    assert slugify("crates/hippo-core/src/storage.rs") == "crates-hippo-core-src-storage-rs"
    assert slugify("  Multiple   Spaces  ") == "multiple-spaces"
    assert slugify("") == "unnamed"


def test_entity_slug_prefers_canonical_falls_back_to_name_then_id():
    assert entity_slug("project", "hippo", "hippo", 42) == "hippo"
    # NULL/empty canonical -> use name
    assert entity_slug("file", "/abs/path.rs", None, 7) == "abs-path-rs"
    # both empty -> use id
    assert entity_slug("concept", "", "", 9) == "entity-9"


def test_node_source_key_agentic_min_session_segment():
    # node links two agentic sessions; pick the min (session_id, segment_index)
    links = {
        "agentic": [("codex", "zzz", 5), ("claude-code", "aaa", 2), ("claude-code", "aaa", 0)],
    }
    assert node_source_key(links, node_type="observation", uuid="u1") == "claude-code-aaa-0"


def test_node_source_key_priority_and_change_outcome_discriminator():
    # workflow + agentic present -> agentic wins by priority; change_outcome gets -co suffix
    links = {"agentic": [("claude-code", "aaa", 0)], "workflow": [101]}
    assert node_source_key(links, node_type="change_outcome", uuid="u2") == "claude-code-aaa-0-co"
    # only workflow
    assert (
        node_source_key({"workflow": [101]}, node_type="change_outcome", uuid="u3") == "wf-101-co"
    )
    # no links at all -> uuid fallback
    assert node_source_key({}, node_type="observation", uuid="u4") == "node-u4"


def _node(**kw):
    base = dict(
        uuid="8f3a",
        source_key="claude-code-aaa-0",
        node_type="observation",
        outcome="success",
        content_json='{"summary":"Fixed FTS trigger backfill in storage.rs. It works now.","intent":"debugging","key_decisions":["Chose porter tokenizer"],"problems_encountered":["FTS rows missing"],"design_decisions":[{"considered":"vec0 only","chosen":"FTS5 | hybrid","reason":"recall\\nmatters"}]}',
        embed_text="storage.rs knowledge_fts porter",
        tags=["hippo", "rust"],
        created_ms=1781530200000,
        updated_ms=1781530302000,
        entities=[
            ("project", "hippo", "entities/project/hippo"),
            ("file", "storage.rs", "entities/file/crates-hippo-core-src-storage-rs"),
        ],
        related=[("claude-code-bbb-1", "FTS trigger backfill")],
        sources=["agentic-session: claude-code/aaa#0"],
    )
    base.update(kw)
    return NodeRow(**base)


def test_render_node_note_frontmatter_round_trips_and_quotes_links():
    md = render_node_note(_node())
    assert md.startswith("<!-- GENERATED BY hippo export vault")
    fm = md.split("---\n")[1]
    data = yaml.safe_load(fm)  # must not raise
    assert data["uuid"] == "8f3a"
    assert data["node_type"] == "observation"
    assert data["related"] == ["[[claude-code-bbb-1|FTS trigger backfill]]"]
    assert data["tags"] == ["hippo", "rust"]
    # ISO8601 with Z
    assert data["created"] == "2026-06-15T13:30:00Z"


def test_render_node_note_derived_headline_truncated_at_sentence():
    md = render_node_note(_node())
    assert "# Fixed FTS trigger backfill in storage.rs" in md
    # full summary still present in the body
    assert "It works now." in md.split("## Summary")[1]


def test_render_node_note_design_decisions_as_list_escapes_pipes_and_newlines():
    md = render_node_note(_node())
    dd = md.split("## Design Decisions")[1]
    # rendered as a list, not a table; literal | preserved, newlines collapsed
    assert "- **Considered** vec0 only" in dd
    assert "FTS5 | hybrid" in dd
    assert "recall matters" in dd  # newline collapsed to space


def test_render_node_note_non_json_content_falls_back():
    md = render_node_note(_node(content_json="not json at all", embed_text="raw tokens here"))
    assert "## Summary" in md
    assert "raw tokens here" in md  # falls back to embed_text
    # frontmatter still valid
    yaml.safe_load(md.split("---\n")[1])


def test_render_node_note_full_outcome_vocab_passthrough():
    for oc in (
        "success",
        "partial",
        "failure",
        "unknown",
        "cancelled",
        "action_required",
        "skipped",
    ):
        md = render_node_note(_node(outcome=oc))
        assert yaml.safe_load(md.split("---\n")[1])["outcome"] == oc


def test_render_entity_page_lists_members_and_omits_last_seen():
    from hippo_brain.vault_render import EntityRow, render_entity_page

    row = EntityRow(
        entity_type="project",
        canonical="hippo",
        first_seen_ms=1704067200000,
        members=[("claude-code-aaa-0", "Fixed FTS"), ("evt-12", "ran cargo test")],
        total_members=2,
        cap=200,
    )
    md = render_entity_page(row)
    fm = yaml.safe_load(md.split("---\n")[1])
    assert fm["type"] == "entity"
    assert fm["entity_type"] == "project"
    assert "last_seen" not in fm  # churn-free: last_seen deliberately omitted
    assert "[[claude-code-aaa-0|Fixed FTS]]" in md
    assert "showing" not in md.lower()  # no truncation note when under cap


def test_render_entity_page_caps_hub_members_with_explicit_note():
    from hippo_brain.vault_render import EntityRow, render_entity_page

    members = [(f"evt-{i}", f"node {i}") for i in range(3)]
    row = EntityRow(
        entity_type="tool",
        canonical="git",
        first_seen_ms=0,
        members=members,
        total_members=5699,
        cap=3,
    )
    md = render_entity_page(row)
    assert "showing 3 of 5699" in md  # no silent truncation


def test_shard_for_uses_created_month():
    from hippo_brain.vault_render import shard_for

    assert shard_for(1781530200000) == "2026-06"


def test_render_root_index_links_to_sub_indexes_not_all_nodes():
    from hippo_brain.vault_render import render_root_index

    md = render_root_index(projects=["hippo", "whistlepost"], months=["2026-06", "2026-05"])
    assert "[[indexes/project-hippo|hippo]]" in md
    assert "[[indexes/month-2026-06|2026-06]]" in md
    # the root index must NOT enumerate individual nodes (unbounded growth guard)
    assert "knowledge/" not in md


def test_compute_related_excludes_hub_entities_and_bounds_topk():
    from hippo_brain.vault_edges import compute_related

    # node 1 shares hub entity 'git'(deg 9999) with everyone, and rare entity
    # 'storage.rs'(deg 2) with node 2 only. Only the rare link should survive.
    node_entities = {
        1: {"git", "storage.rs"},
        2: {"git", "storage.rs"},
        3: {"git"},
    }
    entity_degree = {"git": 9999, "storage.rs": 2}
    related = compute_related(node_entities, entity_degree, hub_degree_cap=200, top_k=8)
    assert related[1] == [2]  # node 3 shares only the excluded hub -> no edge
    assert related[3] == []


def test_compute_related_respects_top_k_ordering_by_rarity_weight():
    from hippo_brain.vault_edges import compute_related

    node_entities = {
        1: {"a", "b", "c"},
        2: {"a"},  # shares rarest
        3: {"b"},
        4: {"c"},
    }
    entity_degree = {"a": 2, "b": 3, "c": 4}
    related = compute_related(node_entities, entity_degree, hub_degree_cap=200, top_k=2)
    assert related[1] == [2, 3]  # top-2 by inverse-degree weight: a > b > c


def test_fetch_exportable_excludes_probe_only_nodes(tmp_db):
    from hippo_brain.vault_export import fetch_exportable_node_ids

    conn, _db_path = tmp_db
    conn.execute(
        "INSERT INTO knowledge_nodes (id, uuid, content, embed_text) VALUES (1,'real','{}','x'),(2,'probe','{}','y')"
    )
    conn.execute(
        "INSERT INTO agentic_sessions (id, session_id, harness, segment_index, project_dir, cwd, summary_text, start_time, end_time, probe_tag) VALUES (10,'s','codex',0,'/p','/c','sum',0,0,NULL),(11,'sp','codex',1,'/p','/c','sum',0,0,'PROBE')"
    )
    conn.execute("INSERT INTO knowledge_node_agentic_sessions VALUES (1,10),(2,11)")
    conn.commit()
    ids = fetch_exportable_node_ids(conn)
    assert ids == [1]  # node 2 is sourced only by a probe-tagged session


def test_reconcile_writes_changed_skips_unchanged_and_gcs_orphans(tmp_path):
    from hippo_brain.vault_export import reconcile_files

    root = tmp_path / "vault"
    (root / "knowledge").mkdir(parents=True)
    stale = root / "knowledge" / "old.md"
    stale.write_text("stale\n")
    keep = root / "knowledge" / "keep.md"
    keep.write_text("v1\n")

    desired = {
        root / "knowledge" / "keep.md": "v1\n",  # unchanged
        root / "knowledge" / "new.md": "fresh\n",  # new
    }
    mtime_before = keep.stat().st_mtime_ns
    summary = reconcile_files(root, desired, managed_subdirs=["knowledge"])

    assert (root / "knowledge" / "new.md").read_text() == "fresh\n"
    assert not stale.exists()  # orphan GC'd
    assert keep.stat().st_mtime_ns == mtime_before  # unchanged not rewritten
    assert summary["written"] == 1 and summary["deleted"] == 1 and summary["unchanged"] == 1


def test_reconcile_gc_scoped_to_managed_subdirs_only(tmp_path):
    from hippo_brain.vault_export import reconcile_files

    root = tmp_path / "vault"
    (root / "knowledge").mkdir(parents=True)
    foreign = root / "user-note.md"  # outside managed subdirs
    foreign.write_text("mine\n")
    reconcile_files(root, {}, managed_subdirs=["knowledge"])
    assert foreign.exists()  # never touched


def test_assert_safe_target_rejects_foreign_obsidian_vault(tmp_path):
    import pytest

    from hippo_brain.vault_export import assert_safe_target

    (tmp_path / ".obsidian").mkdir()
    with pytest.raises(RuntimeError, match="foreign Obsidian vault"):
        assert_safe_target(tmp_path)


def test_assert_safe_target_allows_empty_or_hippo_owned(tmp_path):
    from hippo_brain.vault_export import assert_safe_target, write_vault_meta

    assert_safe_target(tmp_path)  # empty: ok
    write_vault_meta(tmp_path, hippo_version="0.28.7", schema_version=18, config_hash="abc")
    assert_safe_target(tmp_path)  # has our meta: ok


def test_check_format_version_flags_drift(tmp_path):
    import json as _json

    from hippo_brain.vault_export import (
        VAULT_FORMAT_VERSION,
        check_format_version,
        write_vault_meta,
    )

    write_vault_meta(tmp_path, hippo_version="0.28.7", schema_version=18, config_hash="abc")
    meta = _json.loads((tmp_path / "_vault_meta.json").read_text())
    assert meta["vault_format_version"] == VAULT_FORMAT_VERSION
    assert check_format_version(tmp_path) is True  # matches
    meta["vault_format_version"] = 999
    (tmp_path / "_vault_meta.json").write_text(_json.dumps(meta))
    assert check_format_version(tmp_path) is False  # drift detected
