import yaml

from hippo_brain.vault_render import (
    NodeRow,
    entity_slug,
    node_source_key,
    render_node_note,
    slugify,
)


def test_slugify_strips_obsidian_reserved_chars():
    # concept canonicals are raw error text with [ ] : / " and #
    assert slugify("error[E0382]: borrow of moved value") == "error-e0382-borrow-of-moved-value"
    assert slugify("crates/hippo-core/src/storage.rs") == "crates-hippo-core-src-storage-rs"
    assert slugify("  Multiple   Spaces  ") == "multiple-spaces"
    assert slugify("") == "unnamed"


def test_entity_slug_prefers_canonical_falls_back_to_name_then_id():
    assert entity_slug("project", "hippo", "hippo", 42) == "hippo"
    # NULL/empty canonical -> use name
    assert entity_slug("file", "/abs/path.rs", None, 7) == "abs-path-rs"
    # both empty -> use id
    assert entity_slug("concept", "", "", 9) == "entity-9"


def test_node_source_key_agentic_min_session_segment():
    # node links two agentic sessions; pick the min (session_id, segment_index)
    links = {
        "agentic": [("codex", "zzz", 5), ("claude-code", "aaa", 2), ("claude-code", "aaa", 0)],
    }
    assert node_source_key(links, node_type="observation", uuid="u1") == "claude-code-aaa-0"


def test_node_source_key_priority_and_change_outcome_discriminator():
    # workflow + agentic present -> agentic wins by priority; change_outcome gets -co suffix
    links = {"agentic": [("claude-code", "aaa", 0)], "workflow": [101]}
    assert node_source_key(links, node_type="change_outcome", uuid="u2") == "claude-code-aaa-0-co"
    # only workflow
    assert (
        node_source_key({"workflow": [101]}, node_type="change_outcome", uuid="u3") == "wf-101-co"
    )
    # no links at all -> uuid fallback
    assert node_source_key({}, node_type="observation", uuid="u4") == "node-u4"


def _node(**kw):
    base = dict(
        uuid="8f3a",
        source_key="claude-code-aaa-0",
        node_type="observation",
        outcome="success",
        content_json='{"summary":"Fixed FTS trigger backfill in storage.rs. It works now.","intent":"debugging","key_decisions":["Chose porter tokenizer"],"problems_encountered":["FTS rows missing"],"design_decisions":[{"considered":"vec0 only","chosen":"FTS5 | hybrid","reason":"recall\\nmatters"}]}',
        embed_text="storage.rs knowledge_fts porter",
        tags=["hippo", "rust"],
        created_ms=1781530200000,
        updated_ms=1781530302000,
        entities=[
            ("project", "hippo", "entities/project/hippo"),
            ("file", "storage.rs", "entities/file/crates-hippo-core-src-storage-rs"),
        ],
        related=[("claude-code-bbb-1", "FTS trigger backfill")],
        sources=["agentic-session: claude-code/aaa#0"],
    )
    base.update(kw)
    return NodeRow(**base)


def test_render_node_note_frontmatter_round_trips_and_quotes_links():
    md = render_node_note(_node())
    assert md.startswith("<!-- GENERATED BY hippo export vault")
    fm = md.split("---\n")[1]
    data = yaml.safe_load(fm)  # must not raise
    assert data["uuid"] == "8f3a"
    assert data["node_type"] == "observation"
    assert data["related"] == ["[[claude-code-bbb-1|FTS trigger backfill]]"]
    assert data["tags"] == ["hippo", "rust"]
    # ISO8601 with Z
    assert data["created"] == "2026-06-15T13:30:00Z"


def test_render_node_note_derived_headline_truncated_at_sentence():
    md = render_node_note(_node())
    assert "# Fixed FTS trigger backfill in storage.rs" in md
    # full summary still present in the body
    assert "It works now." in md.split("## Summary")[1]


def test_render_node_note_design_decisions_as_list_escapes_pipes_and_newlines():
    md = render_node_note(_node())
    dd = md.split("## Design Decisions")[1]
    # rendered as a list, not a table; literal | preserved, newlines collapsed
    assert "- **Considered** vec0 only" in dd
    assert "FTS5 | hybrid" in dd
    assert "recall matters" in dd  # newline collapsed to space


def test_render_node_note_non_json_content_falls_back():
    md = render_node_note(_node(content_json="not json at all", embed_text="raw tokens here"))
    assert "## Summary" in md
    assert "raw tokens here" in md  # falls back to embed_text
    # frontmatter still valid
    yaml.safe_load(md.split("---\n")[1])


def test_render_node_note_full_outcome_vocab_passthrough():
    for oc in (
        "success",
        "partial",
        "failure",
        "unknown",
        "cancelled",
        "action_required",
        "skipped",
    ):
        md = render_node_note(_node(outcome=oc))
        assert yaml.safe_load(md.split("---\n")[1])["outcome"] == oc
