"""Render knowledge nodes and entities into Obsidian-compatible markdown.

This module is pure: it takes already-fetched rows and returns strings. All
SQLite access lives in vault_export.py. Filenames derive from a STABLE source
key, never the node uuid (re-enrichment re-mints uuids — see the design spec).
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone

import yaml

# Source priority when a node links several source types. Highest first.
_SOURCE_PRIORITY = ("agentic", "workflow", "browser", "shell", "lesson")

_SLUG_STRIP = re.compile(r"[^a-z0-9]+")


def slugify(text: str, maxlen: int = 200) -> str:
    """Lowercase, replace any run of non-alphanumerics with '-', trim dashes.

    Caps the *base* at ``maxlen`` chars so it stays a valid filename component
    (the OS limit is 255 bytes; the atomic writer also appends ".md.tmp"). Real
    "concept" entities can be raw error blobs thousands of chars long, so
    over-long slugs are truncated and disambiguated with an 8-char hash of the
    full slug — deterministic across runs and collision-free for distinct names.

    Note: collision dedup in vault_export may append a short "-N" suffix to this
    base, so the final filename can be a few chars over ``maxlen`` — still far
    under the 255-byte budget (output is ASCII, so chars == bytes), with the
    default ``maxlen`` of 200 leaving ample headroom for the suffix + ".md.tmp".
    """
    s = _SLUG_STRIP.sub("-", text.strip().lower()).strip("-") or "unnamed"
    if len(s) > maxlen:
        digest = hashlib.sha1(s.encode("utf-8")).hexdigest()[:8]
        keep = maxlen - 9  # room for the "-" separator + 8-char hash
        s = s[:keep].rstrip("-") + "-" + digest
    return s


def entity_slug(entity_type: str, name: str, canonical: str | None, entity_id: int) -> str:
    """Stable slug for an entity file: canonical, else name, else id."""
    base = (canonical or "").strip() or (name or "").strip()
    if not base:
        return f"entity-{entity_id}"
    return slugify(base)


def node_source_key(links: dict, node_type: str, uuid: str) -> str:
    """Derive a stable, content-independent filename slug for a knowledge node.

    ``links`` maps source kind -> list of stable identifiers:
      agentic  -> list of (harness, session_id, segment_index)
      workflow -> list of run_id (int)
      browser  -> list of browser_event_id (int)
      shell    -> list of event_id (int)
      lesson   -> list of lesson_id (int)
    """
    for kind in _SOURCE_PRIORITY:
        items = links.get(kind)
        if not items:
            continue
        if kind == "agentic":
            harness, session_id, segment = min(items, key=lambda t: (t[1], t[2]))
            base = f"{harness}-{session_id}-{segment}"
        else:
            prefix = {"workflow": "wf", "browser": "web", "shell": "evt", "lesson": "lesson"}[kind]
            base = f"{prefix}-{min(items)}"
        # change_outcome (CI) nodes can co-link the same agentic session as an
        # observation node; discriminate so they never collide on one filename.
        if node_type == "change_outcome":
            base += "-co"
        return base
    return f"node-{uuid}"


GENERATED_BANNER = "<!-- GENERATED BY hippo export vault — edits are overwritten on next sync -->"


@dataclass
class NodeRow:
    uuid: str
    source_key: str
    node_type: str
    outcome: str | None
    content_json: str
    embed_text: str
    tags: list[str]
    created_ms: int
    updated_ms: int
    entities: list[tuple[str, str, str]]  # (type, display, link_target_path)
    related: list[tuple[str, str]]  # (target_source_key, alias)
    sources: list[str] = field(default_factory=list)


def _iso(ms: int) -> str:
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _headline(summary: str, cap: int = 80) -> str:
    s = " ".join(summary.split())
    if not s:
        return "Untitled knowledge node"
    first = re.split(r"(?<=[.!?])\s", s, maxsplit=1)[0]
    if len(first) > cap:
        first = first[: cap - 1].rstrip() + "…"
    return first


def _one_line(text: str) -> str:
    return " ".join(str(text).split())


def _emit_frontmatter(data: dict) -> str:
    # sort_keys=False preserves our order; default_flow_style=False -> block lists;
    # allow_unicode keeps identifiers intact. PyYAML force-quotes values needing it.
    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return f"---\n{body}---\n"


def render_node_note(node: NodeRow) -> str:
    try:
        content = json.loads(node.content_json)
        if not isinstance(content, dict):
            raise ValueError
    except ValueError, TypeError:
        content = {}

    summary = content.get("summary") or node.embed_text or "(no content)"
    headline = _headline(summary)

    fm = {
        "uuid": node.uuid,
        "type": "knowledge",
        "node_type": node.node_type,
        "outcome": node.outcome or "unknown",
        "intent": content.get("intent", ""),
        "created": _iso(node.created_ms),
        "updated": _iso(node.updated_ms),
        "tags": list(node.tags),
        "related": [f"[[{key}|{alias}]]" for key, alias in node.related],
        "aliases": [headline],
    }

    lines = [GENERATED_BANNER, _emit_frontmatter(fm), f"# {headline}\n"]
    lines.append(f"**Outcome:** {fm['outcome']} · **Intent:** {fm['intent'] or 'n/a'}\n")

    lines.append("## Summary\n")
    lines.append(summary + "\n")

    if content.get("key_decisions"):
        lines.append("## Key Decisions\n")
        lines += [f"- {_one_line(d)}" for d in content["key_decisions"]]
        lines.append("")

    if content.get("problems_encountered"):
        lines.append("## Problems Encountered\n")
        lines += [f"- {_one_line(p)}" for p in content["problems_encountered"]]
        lines.append("")

    if content.get("design_decisions"):
        lines.append("## Design Decisions\n")
        for dd in content["design_decisions"]:
            considered = _one_line(dd.get("considered", ""))
            chosen = _one_line(dd.get("chosen", ""))
            reason = _one_line(dd.get("reason", ""))
            lines.append(
                f"- **Considered** {considered} — **Chose** {chosen} — **Reason** {reason}"
            )
        lines.append("")

    if node.entities:
        lines.append("## Entities\n")
        by_type: dict[str, list[str]] = {}
        for etype, display, target in node.entities:
            by_type.setdefault(etype, []).append(f"[[{target}|{display}]]")
        for etype in sorted(by_type):
            lines.append(f"- {etype}: " + ", ".join(by_type[etype]))
        lines.append("")

    if node.related:
        lines.append("## Related\n")
        lines += [f"- [[{key}|{alias}]]" for key, alias in node.related]
        lines.append("")

    if node.sources:
        lines.append("## Sources\n")
        lines += [f"- {s}" for s in node.sources]
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


@dataclass
class EntityRow:
    entity_type: str
    canonical: str
    first_seen_ms: int
    members: list[tuple[str, str]]  # (node_source_key, headline) — already capped by caller
    total_members: int
    cap: int


def render_entity_page(entity: EntityRow) -> str:
    fm = {
        "type": "entity",
        "entity_type": entity.entity_type,
        "canonical": entity.canonical,
        "first_seen": _iso(entity.first_seen_ms),
        "aliases": [f"{entity.entity_type}: {entity.canonical}"],
    }
    # NOTE: last_seen is intentionally omitted — it is rewritten on every
    # (re-)enrichment and would churn this file's content/mtime every sync.
    lines = [GENERATED_BANNER, _emit_frontmatter(fm), f"# {entity.canonical}\n"]
    lines.append(f"**Type:** {entity.entity_type}\n")
    lines.append("## Nodes\n")
    lines += [f"- [[{key}|{headline}]]" for key, headline in entity.members]
    if entity.total_members > len(entity.members):
        lines.append(f"\n_(showing {len(entity.members)} of {entity.total_members} nodes)_")
    return "\n".join(lines).rstrip() + "\n"


def shard_for(created_ms: int) -> str:
    """knowledge/ sub-folder for a node, derived from immutable created_at month."""
    return datetime.fromtimestamp(created_ms / 1000, tz=timezone.utc).strftime("%Y-%m")


def render_root_index(projects: list[str], months: list[str]) -> str:
    lines = [GENERATED_BANNER, "# hippo knowledge vault\n", "## Projects\n"]
    lines += [f"- [[indexes/project-{slugify(p)}|{p}]]" for p in projects]
    lines.append("\n## Months\n")
    lines += [f"- [[indexes/month-{m}|{m}]]" for m in months]
    return "\n".join(lines).rstrip() + "\n"


def render_sub_index(
    title: str, members: list[tuple[str, str]], total_members: int | None = None
) -> str:
    """A per-project or per-month MOC listing node links (bounded by caller).

    ``members`` is the already-capped slice; ``total_members`` is the true count
    before capping, used to emit a "showing N of M" note so truncation is never
    silent (mirrors render_entity_page).
    """
    lines = [GENERATED_BANNER, f"# {title}\n"]
    lines += [f"- [[{key}|{headline}]]" for key, headline in members]
    if total_members is not None and total_members > len(members):
        lines.append(f"\n_(showing {len(members)} of {total_members} nodes)_")
    return "\n".join(lines).rstrip() + "\n"
